image:
  # -- image repository
  repository: tccr.io/truecharts/thelounge
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: v4.3.0@sha256:d0e5cc55849d0c7761a2a703df5dd5800ea7956af92faa7cfe55778211f81396

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

# -- environment variables. See [image docs](https://hub.docker.com/r/thelounge/thelounge/) for more details.
# @default -- See below
env:
  THELOUNGE_HOME: "/config"

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 10061
        targetPort: 9000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: "/config"
