image:
  repository: tccr.io/truecharts/snipe-it
  pullPolicy: IfNotPresent
  tag: v5.4.1@sha256:8c4dd0e7cd888cf57958e76b56d03b94c6eb0f701f26bc63a618dcba1b55be82

secret: {}

# See more environment variables in the snipe documentation
# https://github.com/linuxserver/docker-snipe-it#parameters
env:
  NGINX_APP_URL: '{{ include "common.names.fullname" . }}:8080'
  MYSQL_USER: snipe-it
  MYSQL_DATABASE: "snipe-it"
  MYSQL_PORT_3306_TCP_PORT: "3306"

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10120
        targetPort: 80

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

envValueFrom:
  MYSQL_PORT_3306_TCP_ADDR:
    secretKeyRef:
      name: mariadbcreds
      key: plainhost
  MYSQL_PASSWORD:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-password

mariadb:
  enabled: true
  mariadbUsername: snipe-it
  mariadbDatabase: snipe-it
  existingSecret: "mariadbcreds"
