image:
  repository: tccr.io/truecharts/jackett
  pullPolicy: IfNotPresent
  tag: v0.20.726@sha256:2f8d4dd737658f84cd9da5ae9aa461c7facf4c8af196aa59f5d0e86c3862a138

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    protocol: HTTP
    ports:
      main:
        targetPort: 9117
        port: 9117

probes:
  liveness:
    path: "/UI/Login"

  readiness:
    path: "/UI/Login"

  startup:
    path: "/UI/Login"

persistence:
  config:
    enabled: true
    mountPath: "/config"
