image:
  repository: tccr.io/truecharts/plex
  pullPolicy: IfNotPresent
  tag: v1.25.7.5604@sha256:cac4783993b63a0f24058e0d1660c848eafbf5b67307c1ad9d46c4a026f8fd27

service:
  main:
    ports:
      main:
        port: 32400
        targetPort: 32400

persistence:
  config:
    enabled: true
    mountPath: "/config"


env:
  ALLOWED_NETWORKS: "172.16.0.0/16"
