image:
  repository: ghcr.io/truecharts/memcached
  pullPolicy: IfNotPresent
  tag: v1.6.14@sha256:6342cf64146b18f021e5632aee8bb91d3c51d5b7119c56c8999960e4f39b4a10

service:
  main:
    ports:
      main:
        port: 11211
        targetPort: 11211
