name: "Apps: Release"

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: gitpush
    container:
      image: ghcr.io/truecharts/devcontainer:v2.2.1
    steps:

      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        name: Checkout
        with:
          fetch-depth: 100
          token: ${{ secrets.BOT_TOKEN }}

      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          repository: truecharts/catalog
          token: ${{ secrets.BOT_TOKEN }}
          path: catalog

      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          repository: truecharts/dh_catalog
          token: ${{ secrets.BOT_TOKEN }}
          path: dh_catalog

      - name: build-and-run
        run: |
          tools/build-release.sh -p --config .github/cr.yaml
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push new App releases
        run: |
          cd catalog
          git config user.name "TrueCharts-Bot"
          git config user.email "bot@truecharts.org"
          git add --all
          git commit -sm "Commit new App releases for TrueCharts" || exit 0
          git push
          cd -
          rm -rf catalog

      - name: Commit and Push new Docker-hub-locked App releases
        run: |
          cd dh_catalog
          git config user.name "TrueCharts-Bot"
          git config user.email "bot@truecharts.org"
          git add --all
          git commit -sm "Commit new App releases for TrueCharts" || exit 0
          git push
          cd -
          rm -rf dh_catalog

      - name: Commit and Push new Helm Charts and docs
        run: |
          git config user.name "TrueCharts-Bot"
          git config user.email "bot@truecharts.org"
          git add --all
          git commit -sm "Commit released Helm Chart and docs for TrueCharts" || exit 0
          git push
